/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class op_sample_jni_JNIServiceImpl */

#ifndef _Included_op_sample_jni_JNIServiceImpl
#define _Included_op_sample_jni_JNIServiceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     op_sample_jni_JNIServiceImpl
 * Method:    invokeJNI
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_op_sample_jni_JNIServiceImpl_invokeJNI
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
